(component
  (type $color (variant (case "red") (case "green" u32) (case "blue" s32)))
  (type $f-param-type (func (param "x" $color) (result s32)))
  (type $f-result-type (func (result $color)))
  (core module $m
    (func (export "f_param") (param i32 i32) (result i32)
      local.get 0)
    (func (export "f_red") (result i32 i32)
      i32.const 0
      i32.const 0)
    (func (export "f_green") (result i32 i32)
      i32.const 1
      i32.const 42)
    (func (export "f_blue") (result i32 i32)
      i32.const 2
      i32.const 99)
  )
  (core instance $i (instantiate $m))
  (alias core export $i "f_param" (core func $f_param))
  (alias core export $i "f_red" (core func $f_red))
  (alias core export $i "f_green" (core func $f_green))
  (alias core export $i "f_blue" (core func $f_blue))
  (func $g_param (type $f-param-type)
    (canon lift (core func $f_param)))
  (func $g_red (type $f-result-type)
    (canon lift (core func $f_red)))
  (func $g_green (type $f-result-type)
    (canon lift (core func $f_green)))
  (func $g_blue (type $f-result-type)
    (canon lift (core func $f_blue)))
  (export "g_param" (func $g_param))
  (export "g_red" (func $g_red))
  (export "g_green" (func $g_green))
  (export "g_blue" (func $g_blue))
)
